const productsCatalog = 
    [
        {
            "product_id": 1001,
            "product_name": "Cuit 1",
            "product_target": "men",
            "product_category": "cuit",
            "product_img": "img/product-1.png",
            "product_price": 69.00,
            "product_color": "some color",
            "product_size": "some size",
            "product_material": "some material",
            "product_designer": "some designer",
        },
        {
            "product_id": 1002,
            "product_name": "Blouse 1",
            "product_target": "women",
            "product_category": "blouse",
            "product_img": "img/product-2.png",
            "product_price": 14.00,
            "product_color": "some color",
            "product_size": "some size",
            "product_material": "some material",
            "product_designer": "some designer",
        },
        {
            "product_id": 1003,
            "product_name": "Jacket 1",
            "product_target": "men",
            "product_category": "jacket",
            "product_img": "img/product-3.png",
            "product_price": 48.00,
            "product_color": "some color",
            "product_size": "some size",
            "product_material": "some material",
            "product_designer": "some designer",
        },
        {
            "product_id": 1004,
            "product_name": "Dress 1",
            "product_target": "women",
            "product_category": "dress",
            "product_img": "img/product-4.png",
            "product_price": 40.00,
            "product_color": "some color",
            "product_size": "some size",
            "product_material": "some material",
            "product_designer": "some designer",
        },
        {
            "product_id": 1005,
            "product_name": "T-shirt 1",
            "product_target": "men",
            "product_category": "t-shirt",
            "product_img": "img/product-5.png",
            "product_price": 10.00,
            "product_color": "some color",
            "product_size": "some size",
            "product_material": "some material",
            "product_designer": "some designer",
        },
        {
            "product_id": 1006,
            "product_name": "Dress 2",
            "product_target": "women",
            "product_category": "dress",
            "product_img": "img/product-6.png",
            "product_price": 45.00,
            "product_color": "some color",
            "product_size": "some size",
            "product_material": "some material",
            "product_designer": "some designer",
        },
        {
            "product_id": 1007,
            "product_name": "Vest 1",
            "product_target": "men",
            "product_category": "vest",
            "product_img": "img/product-7.png",
            "product_price": 28.00,
            "product_color": "some color",
            "product_size": "some size",
            "product_material": "some material",
            "product_designer": "some designer",
        },
        {
            "product_id": 1008,
            "product_name": "Cuit 1",
            "product_target": "women",
            "product_category": "cuit",
            "product_img": "img/product-8.png",
            "product_price": 64.00,
            "product_color": "some color",
            "product_size": "some size",
            "product_material": "some material",
            "product_designer": "some designer",
        },
        {
            "product_id": 1009,
            "product_name": "Jacket 2",
            "product_target": "men",
            "product_category": "jacket",
            "product_img": "img/product-9.png",
            "product_price": 70.00,
            "product_color": "some color",
            "product_size": "some size",
            "product_material": "some material",
            "product_designer": "some designer",
        },
        {
            "product_id": 1010,
            "product_name": "Skirt 1",
            "product_target": "women",
            "product_category": "skirt",
            "product_img": "img/product-10.png",
            "product_price": 20.00,
            "product_color": "some color",
            "product_size": "some size",
            "product_material": "some material",
            "product_designer": "some designer",
        },
        {
            "product_id": 1011,
            "product_name": "T-shirt 2",
            "product_target": "men",
            "product_category": "t-shirt",
            "product_img": "img/product-11.png",
            "product_price": 10.00,
            "product_color": "some color",
            "product_size": "some size",
            "product_material": "some material",
            "product_designer": "some designer",
        },
        {
            "product_id": 1012,
            "product_name": "Pants 1",
            "product_target": "women",
            "product_category": "pants",
            "product_img": "img/product-12.png",
            "product_price": 24.00,
            "product_color": "some color",
            "product_size": "some size",
            "product_material": "some material",
            "product_designer": "some designer",
        },
        {
            "product_id": 1013,
            "product_name": "Jacket 3",
            "product_target": "men",
            "product_category": "jacket",
            "product_img": "img/product-13.png",
            "product_price": 10.00,
            "product_color": "some color",
            "product_size": "some size",
            "product_material": "some material",
            "product_designer": "some designer",
        },
        {
            "product_id": 1014,
            "product_name": "Leggins 1",
            "product_target": "women",
            "product_category": "leggins",
            "product_img": "img/product-14.png",
            "product_price": 18.00,
            "product_color": "some color",
            "product_size": "some size",
            "product_material": "some material",
            "product_designer": "some designer",
        },
        {
            "product_id": 1015,
            "product_name": "T-shirt 3",
            "product_target": "men",
            "product_category": "t-shirt",
            "product_img": "img/product-15.png",
            "product_price": 10.00,
            "product_color": "some color",
            "product_size": "some size",
            "product_material": "some material",
            "product_designer": "some designer",
        },
        {
            "product_id": 1016,
            "product_name": "Leggins 2",
            "product_target": "women",
            "product_category": "leggins",
            "product_img": "img/product-16.png",
            "product_price": 18.00,
            "product_color": "some color",
            "product_size": "some size",
            "product_material": "some material",
            "product_designer": "some designer",
        },
        {
            "product_id": 1017,
            "product_name": "Jacket 4",
            "product_target": "men",
            "product_category": "jacket",
            "product_img": "img/product-17.png",
            "product_price": 69.00,
            "product_color": "some color",
            "product_size": "some size",
            "product_material": "some material",
            "product_designer": "some designer",
        },
        {
            "product_id": 1018,
            "product_name": "Pants 1",
            "product_target": "men",
            "product_category": "pants",
            "product_img": "img/product-18.png",
            "product_price": 24.00,
            "product_color": "some color",
            "product_size": "some size",
            "product_material": "some material",
            "product_designer": "some designer",
        },
        {
            "product_id": 1019,
            "product_name": "Shorts 1",
            "product_target": "men",
            "product_category": "shorts",
            "product_img": "img/product-19.png",
            "product_price": 19.00,
            "product_color": "some color",
            "product_size": "some size",
            "product_material": "some material",
            "product_designer": "some designer",
        },
        {
            "product_id": 1020,
            "product_name": "T-shirt 1",
            "product_target": "women",
            "product_category": "t-shirt",
            "product_img": "img/product-20.png",
            "product_price": 9.00,
            "product_color": "some color",
            "product_size": "some size",
            "product_material": "some material",
            "product_designer": "some designer",
        },
    ];
const cartProducts = [];
const storage = new Vue();
const app = new Vue({
    el: '#app',
    data: {
        currentCategory: {
            category: '',
            subCategory: '',
            products: [],
        },
        currentProduct: {},
        showCartPage: false,
        currentComponent: "main-page-comp",
    },  
    methods: {
        transitionLink(category, subCategory) {
            this.currentCategory.category = category.toLowerCase();
            this.currentCategory.subCategory = subCategory.toLowerCase();
            if(subCategory === '') {
                this.currentCategory.products = productsCatalog.filter(el => {
                    if(el.product_target.toLowerCase() === category.toLowerCase()) {
                        return true;
                    }
                });                
            } else {
                this.currentCategory.products = productsCatalog.filter(el => {
                    if(el.product_target.toLowerCase() === category.toLowerCase() && el.product_category.toLowerCase() === subCategory.toLowerCase()){
                        return true;
                    }
                });
            };
            this.currentComponent = '';
            this.showCartPage = false;
            setTimeout(() => {
                if(category === 'main') {
                    this.currentComponent = "main-page-comp";
                } else this.currentComponent = "category-page-comp";
            }, 500);
        }
    }, 
});